---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-cm
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "db.defaultLabels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations: {{ .Values.annotations }}
  {{- end }}
data:
  {{- range $key, $value := .Values.app.envs }}
  {{ $key | upper }}: {{ $value | quote }}
  {{- end }}
