---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-pma
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: tool
    app.kubernetes.io/name: {{ .Values.name }}-pma
    app.kubernetes.io/version: {{ .Chart.Version }}
    app: {{ .Values.name }}-pma
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    tier: application
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: tool
      app.kubernetes.io/name: {{ .Values.name }}-pma
      app.kubernetes.io/version: {{ .Chart.Version }}
      app: {{ .Values.name }}-pma
      helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
      tier: application
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: tool
        app.kubernetes.io/name: {{ .Values.name }}-pma
        app.kubernetes.io/version: {{ .Chart.Version }}
        app: {{ .Values.name }}-pma
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        tier: application
    spec:
      containers:
      - image: phpmyadmin:latest
        name: phpmyadmin
        env:
        - name: PMA_HOST
          value: {{ .Values.app.envs.MYSQL_HOST | quote }}
        envFrom:
        - secretRef:
            name: {{ .Values.name }}-secrets
        - configMapRef:
            name: {{ .Values.name }}-cm
        ports:
        - containerPort: {{ .Values.pma.port }}
          name: phpmyadmin
        resources:
          requests:
            cpu: 200m
            memory: 1Gi