apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "db.defaultLabels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.app.secrets }}
  {{ $key | upper }}: {{ $value | b64enc }}
  {{- end }}