apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name | quote }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "db.defaultLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "db.defaultLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "db.defaultLabels" . | nindent 8 }}
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        envFrom:
        - secretRef:
            name: {{ .Values.name }}-secrets
        - configMapRef:
            name: {{ .Values.name }}-cm
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Values.name }}-pvc