apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}-pv
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helper.defaultLabels" . | nindent 4 }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ default "10Gi" .Values.app.storageSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helper.defaultLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "10Gi" .Values.app.storageClaimSize }}