---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helper.defaultLabels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
  selector:
    {{- include "helper.defaultLabels" . | nindent 4 }}
